### ISSUE TITLE
Error while settuping virtualenv on OSX 10.14.2

### ISSUE THREAD

**Issue by magicbadger** [ebu/radiodns-manager#135]
When creating the virtualenv, the following error is logged while installing dependencies:

```
Collecting MySQL-python==1.2.5 (from RadioDns-PlugIt==3.0.0)
  Using cached https://files.pythonhosted.org/packages/a5/e9/51b544da85a36a68debe7a7091f068d802fc515a3a202652828c73453cad/MySQL-python-1.2.5.zip
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/kn/lmwtgy4x6w3fj5g7l71xlq0c0000gn/T/pip-install-bzvhg4au/MySQL-python/setup.py", line 13, in <module>
        from setup_posix import get_config
      File "/private/var/folders/kn/lmwtgy4x6w3fj5g7l71xlq0c0000gn/T/pip-install-bzvhg4au/MySQL-python/setup_posix.py", line 2, in <module>
        from ConfigParser import SafeConfigParser
    ModuleNotFoundError: No module named 'ConfigParser'
```

**Comment by magicbadger** [comment]
The script `setup-envs.sh` expects a `python2` on the path, which will fail if there is just a `python`.

Recommend testing for both and filling a variable before calling.
